// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thumnet.CoverageReport.Data;

namespace Thumnet.CoverageReport.Data.Migrations
{
    [DbContext(typeof(CoverageContext))]
    partial class CoverageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Thumnet.CoverageReport.Core.Entities.CoverageEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BranchName");

                    b.Property<string>("BuildId");

                    b.Property<DateTime>("Created");

                    b.Property<byte[]>("LcovData");

                    b.Property<int>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Thumnet.CoverageReport.Core.Entities.FileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Bytes");

                    b.Property<string>("Checksum");

                    b.HasKey("Id");

                    b.ToTable("FilesData");
                });

            modelBuilder.Entity("Thumnet.CoverageReport.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Thumnet.CoverageReport.Core.Entities.SourceFileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CoverageEntryId");

                    b.Property<int>("DataId");

                    b.Property<string>("FilePath");

                    b.HasKey("Id");

                    b.HasIndex("CoverageEntryId");

                    b.HasIndex("DataId");

                    b.ToTable("SourceFiles");
                });

            modelBuilder.Entity("Thumnet.CoverageReport.Core.Entities.CoverageEntry", b =>
                {
                    b.HasOne("Thumnet.CoverageReport.Core.Entities.Project", "Project")
                        .WithMany("Entries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thumnet.CoverageReport.Core.Entities.SourceFileEntry", b =>
                {
                    b.HasOne("Thumnet.CoverageReport.Core.Entities.CoverageEntry", "CoverageEntry")
                        .WithMany("SourceFiles")
                        .HasForeignKey("CoverageEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thumnet.CoverageReport.Core.Entities.FileData", "Data")
                        .WithMany()
                        .HasForeignKey("DataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
